### ISSUE TITLE
Failing on certain jobs

### ISSUE THREAD

**Issue by ewjoachim** [novafloss/jenkins-epo#289]
On a PR whose only params are :
```yml
jenkins:
  jobs: [rh2*, -rh2-ansible*, -rh2*docker]      # PR python
  # jobs: rh2-db
```

We get, when switching VERBOSE to 1, the following logs:
```
=wk01= Failed to process https://github.com/redacted/redacted/tree/redacted: 'NoneType' object is not iterable
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/jenkins_epo/workers.py", line 75, in worker
res = yield from task
File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
yield self  # This tells Task to wait for completion.
File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
value = future.result()
File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
raise self._exception
File "/usr/lib/python3.4/asyncio/tasks.py", line 235, in _step
result = coro.send(value)
File "/usr/local/lib/python3.4/dist-packages/jenkins_epo/procedures.py", line 93, in process_url
yield from bot.run(head)
File "/usr/local/lib/python3.4/dist-packages/jenkins_epo/bot.py", line 145, in run
yield from ext.run()
File "/usr/local/lib/python3.4/dist-packages/jenkins_epo/extensions/jenkins.py", line 278, in run
for action, spec in self.process_job_specs()
File "/usr/local/lib/python3.4/dist-packages/jenkins_epo/extensions/jenkins.py", line 277, in <listcomp>
loop.create_task(self.process_job(action, spec))
File "/usr/local/lib/python3.4/dist-packages/jenkins_epo/extensions/jenkins.py", line 229, in process_job_specs
if not current_job.spec.contains(spec):
File "/usr/local/lib/python3.4/dist-packages/jenkins_yml/job.py", line 195, in contains
missing = set(their['parameters']) - set(my['parameters'])
TypeError: 'NoneType' object is not iterable
```

It seems that either `their` or `my` have a `"parameter"` key at None... Strange thing is that it worked yersterday and suddenly stopped working.

I'll update the ticket if I find new interesting information.

**Comment by ewjoachim** [comment]
Ah, ok. It happens if you add and then remove the "parameters" of a job in jenkins.yml. And as the traceback says, this is a problem from jenkins-yml and not epo.
